### PR TITLE
Update release notes for OHIF

### PR DESCRIPTION
**Pull request by igoroctaviano**
- Update release notes for OHIF up to 4.12.45 (final version before v3)

### CODE REVIEW

**Comment by fedorov** [comment]
Per discussion today, let's implement a basic procedure to mark versions of IDC fork, label clearly that those versions do not correspond to the OHIF v2 upstream and is an IDC "branch" of v2. And let's not label it as "deprecated" in the IDC release notes, because for IDC it is definitely not deprecated.

**Comment by igoroctaviano** [comment]
> procedure to mark versions of IDC fork, label clearly that those versions do not correspond to the OHIF v2 upstream and is an IDC "branch" of v2. And let's not label it as "deprecated" in the IDC release notes, because for IDC it is definitely not deprecated.

PR updated. Ticket created: https://github.com/ImagingDataCommons/Viewers/issues/207

**Comment by fedorov** [comment]
Thank you @igoroctaviano! I will keep this open for now, until we do the release, and then merge.

**Comment by fedorov** [comment]
unfortunately, there is some issue between github and gitbook right now, and I cannot sync, so not merging yet...

**Pull request merged**
