### PR TITLE
Update viewer-release-notes with slim releases

### PR DESCRIPTION
**Pull request by Punzo**
@fedorov @hackermd

### CODE REVIEW

**Comment by Punzo** [comment]
added slim releases info and a screenshot in the IDC viewers descriptions

**Comment by fedorov** [comment]
@hackermd would you like to review before this is merged?

**Comment by hackermd** [comment]
LGTM. Thanks @Punzo

**Comment by fedorov** [comment]
Great, thanks! 

I know GitBook is going through a massive upgrade to the next release, so I will keep this unmerged until I confirm with GitBook support it's ok to change our content.

**Review by hackermd — APPROVED** [review]

**Comment by hackermd** [comment]
@fedorov @Punzo I just realized a new patch version of Slim ([v0.4.3](https://github.com/MGHComputationalPathology/slim/releases/tag/v0.4.3)) and it would be great if that version could be included.

**Comment by Punzo** [comment]
> @fedorov @Punzo I just realized a new patch version of Slim ([v0.4.3](https://github.com/MGHComputationalPathology/slim/releases/tag/v0.4.3)) and it would be great if that version could be included.

done in https://github.com/ImagingDataCommons/IDC-Docs/pull/16/commits/5151bbac9317c894d2267c052b356a2933d6fd3f and I opened a PR to update the IDC fork https://github.com/ImagingDataCommons/slim/pull/44

**Review by hackermd — APPROVED** [review]

**Pull request merged**
