### PR TITLE
add viewer release note Sept

### PR DESCRIPTION
**Pull request by Punzo**
See https://github.com/ImagingDataCommons/Viewers/pull/98

### CODE REVIEW

**Comment by Punzo** [comment]
@fedorov

**Comment by fedorov** [comment]
@Punzo thank you for updating the release notes, but I think release notes for the IDC docs should match the version of the viewer available in the production tier. IDC release was done couple of weeks ago in August, and the viewer version I see is 4.9.20. What do you think?

**Comment by Punzo** [comment]
@fedorov I agree the documentation should be in sync with the production tier portal. So this can wait to be merged (but we will have it ready). 

I missed the release in August (did you commit something on the IDC side?), because version 4.9.20 from the OHIF side is from June: 
gnome-shell-screenshot-M4OF90

So I think https://github.com/ImagingDataCommons/IDC-Docs/blob/pilot/portal/viewer-release-notes.md#4919---june-2020 should have been 4.9.20 instead of 4.9.19 (my fault! and I am not sure why we have the same day two releases on OHIF, maybe there were two PRs and I forgot to wait). Should I open another PR for this? or may you change the number on master directly?

**Comment by fedorov** [comment]
I think we need to have release notes that match the viewer in production latest release. The notes you provided list 4.10.1. Are you saying I should replace 4.10.1 with 4.9.20 after I merge your PR?

**Comment by Punzo** [comment]
sorry @fedorov for not being clear. I mean:
1) independently by this PR, the current first line https://github.com/ImagingDataCommons/IDC-Docs/blob/pilot/portal/viewer-release-notes.md#4919---june-2020 should have 4.9.20 instead of 4.9.19 as number. I have opened a PR, see https://github.com/ImagingDataCommons/IDC-Docs/pull/14
2) Then we can merge this PR when production tier portal will be updated with current IDC Vierwer master fork (OHIF version 4.10.1) (PR already merged https://github.com/ImagingDataCommons/Viewers/pull/98).

**Pull request merged**
